    @startuml
    left to right direction
    skinparam linetype ortho

    package it.univr {
        rectangle Main
        rectangle App
        package ui {
            package panes {
                rectangle GraphSidePane
                rectangle MagicLayoutSidePane
                rectangle MainPane 
                rectangle SolutionPane
            } 
            package smallComponents {
                rectangle PathEdgeNode
                rectangle PathVertexNode
                rectangle IconButton
            }
            package popups {
                rectangle ClosePopup
                rectangle ConfirmPopup
                rectangle EdgePopup
                rectangle ErrorPopup
                rectangle TutorialPopup
                rectangle VertexPopup
            }   
        } 
        
        package utils {
            rectangle Constants 
            rectangle GraphToFile
            rectangle TestGraphAlgorithm
            rectangle SceneReference 
        }
       
        
        MainPane *--> GraphSidePane
        MagicLayoutSidePane <--* MainPane
        MainPane *----> SolutionPane    
        PathEdgeNode <----o SolutionPane
        popups  --- MainPane : shows <
        PathVertexNode <---o SolutionPane
        IconButton <---o GraphSidePane
        Main .--> App
        App .> MainPane
        panes .> SceneReference
        popups .---> SceneReference
        SolutionPane .> TestGraphAlgorithm
        GraphToFile .-> MainPane
    }
    @enduml