@startuml

package Controller.popups {
   skinparam classAttributeIconSize 0
    
class VertexPopup {
    - Stage stage
    - static DigraphEdgeList<String, String> graph
    - static SmartGraphPanel<String, String> graphView
    - String vertexName
    - static int count
    - static SimpleBooleanProperty initialVertexSetProperty
    - Button cancelButton
    - Button submitButton
    - TextField vertexNameField
    - CheckBox initialVertexCheckBox
    - CheckBox finalVertexCheckBox
    - Text errorText
    + VertexPopup()
    - addVertex()
    - updateSpecialVertices(SmartGraphVertexNode<String>)
    + initialize()
}
class ConfirmPopup {
    - String confirmType
    - String confirmString
    - Runnable onConfirm
    - Text confirmText
    - Text confirmTypeText
    - Button confirmButton
    - Button cancelButton
    + ConfirmPopup(String, String, Runnable)
    + initialize()
}  
class ClosePopup {
    - Button dontButton
    - Button cancelButton
    - Button saveButton
    + ClosePopup()
    + initialize()
}   

class ErrorPopup {
    - String errorMsg
    - String errorType
    - Stage stage
    - Text errorText
    - Text titleText
    - Button closeButton
    + ErrorPopup(String, String)
    + initialize()
}
class TutorialPopup {
    - HBox nodesImagesBox
    - TextFlow tutorial
    - TextFlow rules
    - Button closeButton
    + TutorialPopup()
    + initialize()
    - vertexLegend()
}
class EdgePopup {
    - Stage stage
    - MainPane mainPane
    - SmartGraphVertexNode from
    - SmartGraphVertexNode to
    - Button cancelButton
    - Button submitButton
    - TextField edgeNameField
    - Text errorText
    + EdgePopup(SmartGraphVertexNode, SmartGraphVertexNode)
    - addEdge()
    + initialize()
}

}

@enduml