@startuml
skinparam dpi 400
left to right direction
skinparam packageStyle rectangle
actor User
rectangle WordAutomata {
    usecase "aggiungi stato" as UCVAdd
    usecase "aggiungi transizione" as UCEAdd
    User -- (carica / importa automa)
    User -- (salva / esporta automa) 
    usecase "modifica automa" as UCMod
    usecase "modifica stato" as UCVMod
    usecase "modifica transizione" as UCEMod
    usecase "inserisci parola test" as UCTW
    usecase "calcola percorso" as UCCP
    usecase "modifica layout Automa" as UCLMod
}

User -- UCCP
User -- UCLMod
User --- UCMod 
User -- UCVAdd
User -- UCEAdd

UCMod <-. UCVMod : <<extend>>
UCMod <-. UCEMod : <<extend>>
UCCP .-> UCTW : <<include>>


@enduml